---
  - name: Install Metricbeat
    hosts: webservers
    become: true
    tasks:
      # Download.deb
      - name: Download.metric.deb
        command: curl https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb -O

      # Install metricbeat
      - name: Download metricbeat.deb
        command: dpkg -i metricbeat-7.4.0-amd64.deb

      # Copy metric config
      - name: Copy config files
        copy:
         src: /etc/ansible/files/metricbeat-config.yml
         dest: /etc/metricbeat/metricbeat.yml

      # Setup metricbeat
      - name: Allow Modules System
        command: metricbeat modules enable system

      # Metricbeat setup
      - name: Metricbeat setup
        command: metricbeat setup

      # Metricbeat -e
      - name: Metricbeat -e
        command: sudo service metricbeat start